### ISSUE TITLE
Supply a docker-free setup.py script

### ISSUE THREAD

**Issue by froggleston** [collaborative-open-plant-omics/COPO#13]
Deploying COPO by hand is very time-consuming, so a setup.py script to help users who aren't using Docker to install would be a good thing to have.

**Comment by shaw2thefloor** [comment]
started

**Comment by shaw2thefloor** [comment]
working for OSX and Ubuntu.....Rob to test on his machine.

**Comment by shaw2thefloor** [comment]
Tony....can you test it as well when you get a moment....I want to see if it works when the user has an existing Postgres and Mongo system.
